# ДОБАВЛЕНО: Объявляем зону кэша STATIC, чтобы Nginx не падал!
proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=STATIC:10m max_size=1g inactive=7d use_temp_path=off;

# 1. HTTP — редирект на HTTPS и проверка Certbot
server {
    listen 80;
    listen [::]:80;
    server_name auracomplexnew.ru www.auracomplexnew.ru;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# 2. HTTPS — основной сервер
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name auracomplexnew.ru www.auracomplexnew.ru;
    server_tokens off;
    underscores_in_headers on;

    resolver 127.0.0.11 valid=30s;

    ssl_certificate /etc/letsencrypt/live/auracomplexnew.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/auracomplexnew.ru/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    gzip on;
    gzip_proxied any;
    gzip_comp_level 4;
    gzip_types text/css application/javascript image/svg+xml;

    location /_next/static {
        proxy_cache STATIC;
        proxy_cache_valid 200 60m; # Добавили время валидности кэша
        set $upstream_static http://nextjs_app:3000;
        proxy_pass $upstream_static;
    }

    location /api/ {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_cache_bypass $http_upgrade;
        proxy_no_cache 1;
        proxy_cache_bypass 1;

        set $upstream_api http://nextjs_app:3000;
        proxy_pass $upstream_api;
    }

    location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        set $upstream_main http://nextjs_app:3000;
        proxy_pass $upstream_main;
    }
}